services:

  localstack:
    image: localstack/localstack
    container_name: "localstack-spring-sqs-integration-example"
    environment:
      - SERVICES=sqs
      - DEFAULT_REGION=sa-east-1
      - DEBUG=1
      - DATA_DIR=/tmp/localstack/data
    ports:
      - "4566:4566"
    networks:
      - localstack-network

  terraform:
    image: hashicorp/terraform:1.3.3
    container_name: "terraform-spring-sqs-integration-example"
    volumes:
      - ./infra/terraform/:/infra
    working_dir: /infra
    depends_on:
      - localstack
    networks:
      - localstack-network
    entrypoint: >
      sh -c "
      terraform init
      && terraform fmt
      && terraform validate
      && terraform plan -out='infra.out'
      && terraform apply infra.out"

networks:
  localstack-network:
    driver: bridge